/* This file is autogenerated from the database. */
/* See src/desc/gen_proto */
/* Do not edit*/
entree functions_gp[]={
{"alarm",0,(void*)alarm0,11,"vD0,L,","alarm({s = 0}): trigger an \"alarmer\" exception after s seconds, cancelling any previously set alarm. Stop a pending alarm if s = 0 or is omitted."},
{"allocatemem",0,(void*)allocatemem0,11,"vDG","allocatemem({s=0}): allocates a new stack of s bytes. doubles the stack if s is omitted."},
{"extern",0,(void*)extern0,11,"s","extern(str): execute shell command str, and feeds the result to GP (as if loading from file)."},
{"externstr",0,(void*)externstr,11,"s","externstr(str): execute shell command str, and returns the result as a vector of GP strings, one component per output line."},
{"input",0,(void*)input0,11,"","input(): read an expression from the input file or standard input."},
{"quit",0,(void*)gp_quit,11,"vD0,L,","quit({status = 0}): quit, return to the system with exit status 'status'."},
{"read",0,(void*)read0,11,"D\"\",s,","read({filename}): read from the input file filename. If filename is omitted, reread last input file, be it from read() or \\r."},
{"system",0,(void*)system0,11,"vs","system(str): str being a string, execute the system command str."},
{"whatnow",0,(void*)whatnow0,11,"vr","whatnow(key): if key was present in GP version 1.39.15 or lower, gives the new function name."},
{NULL,0,NULL,0,NULL,NULL} /* sentinel */
};
